### ISSUE TITLE
NULL arguments...

### ISSUE THREAD

**Issue by pulgamecanica** [BrenoMachado123/42-Projects#10]
https://github.com/BrenoMachado123/42-Projects/blob/f3251b04735b2d716de0f986b40aabc03e55631e/Minishell/cmd_lst.c#L107

The argument `token_lst` is always initialized in the function as NULL, in the main you set it to NULL. Also I am not sure why you decided to pass it as an argument. As I say it's ALWAYS a NULL argument.
In my opinion it should not be even an argument of the function.

**Comment by BrenoMachado123** [comment]
Well... I am not sure why I decided to pass as an argument either 🤔
Maybe I was coding something before that needed to do it but then I changed and forgot to fix that part.
Anyway, still a ugly mistake, my bad.

**Comment by BrenoMachado123** [comment]
Solved!
