### ISSUE TITLE
Length of an array char **

### ISSUE THREAD

**Issue by pulgamecanica** [BrenoMachado123/42-Projects#3]
https://github.com/BrenoMachado123/42-Projects/blob/f3251b04735b2d716de0f986b40aabc03e55631e/Minishell/env_table.c#L15

https://github.com/BrenoMachado123/42-Projects/blob/f3251b04735b2d716de0f986b40aabc03e55631e/Minishell/libft/ft_arrlen.c#L15

len_env[env_table.c] is the SAME as ft_arrlen from libft...

**Comment by BrenoMachado123** [comment]
solved!
