### ISSUE TITLE
Malloc Protection

### ISSUE THREAD

**Issue by pulgamecanica** [BrenoMachado123/42-Projects#5]
https://github.com/BrenoMachado123/42-Projects/blob/f3251b04735b2d716de0f986b40aabc03e55631e/Minishell/local_utils.c#L23

I encourage to protect the `var` malloc right after it was allocated, this is because if it fails, then it would segfault when you try to do:
```
	var->key = ft_strdup(key);
	var->value = ft_strdup(value);
```
`var->key && var->value` can be checked togeather that's ok.

_(I blame the NORM!!! we are always trying to save lines haha)_

**Comment by BrenoMachado123** [comment]
Solved!!!
