### ISSUE TITLE
Extra lines

### ISSUE THREAD

**Issue by pulgamecanica** [BrenoMachado123/42-Projects#6]
https://github.com/BrenoMachado123/42-Projects/blob/f3251b04735b2d716de0f986b40aabc03e55631e/Minishell/local_utils.c#L25
https://github.com/BrenoMachado123/42-Projects/blob/f3251b04735b2d716de0f986b40aabc03e55631e/Minishell/local_utils.c#L26

More extra lines.
Let this issue serve as a track, in order to remember it.

**Comment by BrenoMachado123** [comment]
Solved!
