### ISSUE TITLE
Rigor

### ISSUE THREAD

**Issue by pulgamecanica** [BrenoMachado123/42-Projects#8]
https://github.com/BrenoMachado123/42-Projects/blob/f3251b04735b2d716de0f986b40aabc03e55631e/Minishell/local_utils.c#L58

I think this function should be at free.c would make more sence, what do you think? So the code is more rigorous.

**Comment by BrenoMachado123** [comment]
And we can move the "join_args" function from free.c as well, I created it there just for some tests but I forgot to move from somewhere else after the tests

**Comment by BrenoMachado123** [comment]
Solved!
